name: Deploy from dev branch

on:
  # Запускать при пуше в ветку dev
  push:
    branches: ["dev"]
  # Разрешить запуск вручную из вкладки Actions
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Важно: указываем явно ветку dev
          ref: "dev"

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Copy files from frontend/docs
        run: |
          # Копируем всё содержимое frontend/docs
          cp -r frontend/docs/* ./
          # Копируем скрытые файлы (если есть)
          cp -r frontend/docs/.* . 2>/dev/null || true
          # Проверяем что скопировалось
          ls -la

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./

  deploy:
    environment:
      name: github-pages-dev
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
